import './globals.css';
import { Poppins } from 'next/font/google';
import { Footer } from './components';

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '600', '700'] });

export const metadata = {
    title: 'Expense Tracker',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html data-theme="night" lang="en">
            <body className={poppins.className}>
                {children}
            </body>
            <Footer />
        </html>
    );
}
